Repository coreos/rpm-ostree, pull requests merged in 2019-10, with the labels that each got.

#1915 ci: Also bump MSRV to 1.37.0 for CCI Jenkins
  .cci.jenkinsfile
  .papr.yml
  ci/msrv.sh
Labels: approved, lgtm

#1917 app/reset: Fix argc range check
  src/app/rpmostree-builtin-reset.c
Labels: approved, lgtm, size/XS

#1893 More prow CI work
  ci/build-check.sh
  ci/installdeps.sh
  ci/prow/Dockerfile
Labels: approved, lgtm, size/S

#1914 rust/lockfile: Add YAML support
  rust/src/lockfile.rs
  rust/src/treefile.rs
  rust/src/utils.rs
Labels: approved, lgtm, reviewed/approved, size/L

#1918 ci/papr: Drop cosa build
  .papr.yml
Labels: approved, lgtm, size/S

#1911 Add hidden `coreos-rootfs seal` command
  Makefile-rpm-ostree.am
  rust/Cargo.lock
  rust/Cargo.toml
  rust/src/coreos_rootfs.rs
  rust/src/lib.rs
  src/app/main.c
  src/app/rpmostree-builtin-coreos-rootfs.c
  src/app/rpmostree-builtins.h
  tests/vmcheck/test-misc-1.sh
Labels: approved, lgtm, size/L

#1922 tests/vmcheck: Fix test-misc-1.sh syntax
  tests/vmcheck/test-misc-1.sh
Labels: approved, lgtm, size/XS

#1923 ci/papr: Drop `required` branch
  .papr.yml
Labels: approved, lgtm, size/XS

#1926 unpacker: Build with older libarchive without zstd
  configure.ac
  src/libpriv/rpmostree-unpacker-core.c
Labels: approved, lgtm, size/XS

#1927 core: Filter locked packages by checksums before depsolving
  src/libpriv/rpmostree-core.c
Labels: approved, lgtm, size/S

#1931 HACKING.md: Document libdnf vendoring rationale
  HACKING.md
Labels: approved, lgtm, size/S

#1932 Detect whether zchunk (zck) is available at build time
  configure.ac
  packaging/rpm-ostree.spec.in
  src/libpriv/rpmostree-core.c
Labels: approved, lgtm, size/S

#1934 libpriv/kernel: Hack around vmlinuz path in HMAC file
  src/libpriv/rpmostree-kernel.c
Labels: approved, lgtm, size/M
