Repository coreos/rpm-ostree, pull requests merged in 2020-02, with the labels that each got.

#1974 importer: Use /run instead of /var/run
  src/libpriv/rpmostree-importer.c
  tests/compose/test-basic-unified.sh
Labels: approved, lgtm, size/S

#1980 treefile: Add exclude-packages
  docs/manual/treefile.md
  rust/src/treefile.rs
  src/app/rpmostree-composeutil.c
  src/libpriv/rpmostree-core.c
  tests/common/libtest-core.sh
  tests/compose/test-excludes.sh
  tests/compose/test-misc-tweaks.sh
Labels: approved, lgtm, size/M

#1981 Release 2020.1
  configure.ac
  packaging/rpm-ostree.spec.in
Labels: approved, lgtm, size/XS

#1984 core,kernel: Set up /etc/passwd for dracut
  src/libpriv/rpmostree-core.c
  src/libpriv/rpmostree-core.h
  src/libpriv/rpmostree-kernel.c
  src/libpriv/rpmostree-passwd-util.h
  tests/vmcheck/test-initramfs.sh
Labels: approved, lgtm, size/L

#1999 ci: Pull Fedora from api.ci
  tests/common/libvm.sh
Labels: approved, lgtm, size/XS
