Repository coreos/rpm-ostree, pull requests merged in 2020-01, with the labels that each got.

#1961 core: Mark all repos as "modular hotfixes"
  src/libpriv/rpmostree-core.c
  tests/compose/test-basic.sh
Labels: approved, lgtm, size/S

#1962 libpriv/util: Fix human diff printing for upgrades/downgrades
  src/libpriv/rpmostree-util.c
  tests/vmcheck/test-db.sh
Labels: approved, lgtm, size/M

#1972 treefile: Use ref_from_raw_ptr
  rust/src/treefile.rs
Labels: approved, lgtm, size/XS
