Repository coreos/rpm-ostree, pull requests merged in 2020-05, with the labels that each got.

#2081 ci: Download the latest ostree even if from stable repos
  .cci.jenkinsfile
Labels: approved, lgtm

#2077 s/RPM-OSTree/rpm-ostree/
  docs/manual/background.md
  man/rpm-ostreed.conf.xml
  rust/src/history.rs
  src/app/rpmostree-builtin-ex.c
  src/app/rpmostree-compose-builtin-tree.c
  src/daemon/rpm-ostree-bootstatus.service.in
  src/daemon/rpm-ostreed-automatic.service.in
  src/daemon/rpm-ostreed-automatic.timer
  src/daemon/rpm-ostreed.service.in
Labels: approved, lgtm

#2079 ci-commitmessage-submodules: Ignore empty merge commits
  ci/ci-commitmessage-submodules.sh
Labels: approved, lgtm

#2078 tests: Trim out dead code from libtest.sh, rework SRCDIR
  tests/common/libtest.sh
Labels: approved, lgtm

#2089 Makefile.am: Link with --enable-new-dtags
  Makefile-lib.am
  Makefile.am
Labels: approved, lgtm

#2088 tests: Move more code to kola
  tests/kola/nondestructive/misc.sh
  tests/vmcheck/test-misc-1.sh
Labels: approved, lgtm

#2080 treefile: Add readonly-executables
  docs/manual/treefile.md
  rust/src/treefile.rs
  src/libpriv/rpmostree-core.c
  src/libpriv/rpmostree-importer.c
  src/libpriv/rpmostree-importer.h
  tests/compose/test-misc-tweaks.sh
Labels: approved, lgtm

#2037 Recognize other kernel packages with provides
  src/libpriv/rpmostree-core.c
Labels: approved, lgtm, ok-to-test

#2093 build-sys: Remove --enable-new-name
  Makefile-daemon.am
  Makefile-rpm-ostree.am
  Makefile.am
  configure.ac
Labels: approved, lgtm

#2091 Release 2020.2
  configure.ac
Labels: approved, lgtm

#2092 build-sys: Disable zchunk for libdnf if we don't have it
  configure.ac
Labels: approved, lgtm

#2096 upgrader: Reset ref before fetching commit by override
  src/daemon/rpmostree-sysroot-upgrader.c
Labels: approved, lgtm

#2095 docs/background: Fix benefits and drawbacks formatting
  docs/manual/background.md
Labels: approved, lgtm, needs-ok-to-test

#2104 compose: Remove --output-repodata-dir
  src/app/rpmostree-compose-builtin-tree.c
Labels: approved, lgtm

#2098 compose: Add a "warn and sleep" if --unified-core is not provided
  docs/manual/compose-server.md
  src/app/rpmostree-compose-builtin-tree.c
Labels: approved, lgtm

#2105 spec: Fix up conditionals for ELN
  packaging/rpm-ostree.spec.in
Labels: approved, lgtm

#2106 tests/kola: Move into tests/kolainst, run installed
  .cci.jenkinsfile
  tests/kola/nondestructive/data
  tests/kolainst/Makefile
  tests/kolainst/nondestructive/misc.sh
Labels: approved, lgtm

#2108 rojig-build: Just expand %_isa
  src/libpriv/rpmostree-rojig-build.c
Labels: approved, lgtm

#2111 daemon: Add an error prefix in local repo pulls
  src/daemon/rpmostreed-transaction-types.c
Labels: approved, lgtm

#2110 rebase: Remove requirement for --experimental with local rebases
  src/app/rpmostree-builtin-rebase.c
  tests/vmcheck/test-misc-2.sh
Labels: approved, lgtm
