Repository coreos/rpm-ostree, pull requests merged in 2021-03, with the labels that each got.

#2615 daemon: Fix crash on upgrade with remote:checksum
  src/daemon/rpmostree-sysroot-upgrader.cxx
  tests/vmcheck/test-pinned-commit.sh
Labels: approved, lgtm

#2621 client: Remove peer_pid value from option parsing
  src/app/libmain.cxx
  src/app/rpmostree-builtin-applylive.cxx
  src/app/rpmostree-builtin-cancel.cxx
  src/app/rpmostree-builtin-cleanup.cxx
  src/app/rpmostree-builtin-db.cxx
  src/app/rpmostree-builtin-deploy.cxx
  src/app/rpmostree-builtin-finalize-deployment.cxx
  src/app/rpmostree-builtin-initramfs-etc.cxx
  src/app/rpmostree-builtin-initramfs.cxx
  src/app/rpmostree-builtin-kargs.cxx
  src/app/rpmostree-builtin-rebase.cxx
  src/app/rpmostree-builtin-refresh-md.cxx
  src/app/rpmostree-builtin-reload.cxx
  src/app/rpmostree-builtin-reset.cxx
  src/app/rpmostree-builtin-rollback.cxx
  src/app/rpmostree-builtin-status.cxx
  src/app/rpmostree-builtin-upgrade.cxx
  src/app/rpmostree-builtin-usroverlay.cxx
  src/app/rpmostree-builtins.h
  src/app/rpmostree-compose-builtin-tree.cxx
  src/app/rpmostree-dbus-helpers.cxx
  src/app/rpmostree-dbus-helpers.h
  src/app/rpmostree-override-builtins.cxx
  src/app/rpmostree-pkg-builtins.cxx
Labels: approved, lgtm

#2622 tests/vmcheck: Use .cosa over COSA_DIR
  tests/common/libvm.sh
Labels: approved, lgtm

#2624 ex: Drop erroneous REQUIRES_ROOT flag on apply-live, initramfs-etc
  src/app/rpmostree-builtin-ex.cxx
Labels: approved, lgtm

#2620 tests/apply-live: Upgrade+liveapply no-package changes
  tests/vmcheck/test-apply-live.sh
Labels: approved, lgtm

#2628 cxxrsutil: Generalize cxxrs_bind! macro
  rust/src/cxxrsutil.rs
Labels: approved, lgtm

#2623 tests: Add RPMs to installed kola tests, port layering-local
  tests/common/libtest.sh
  tests/kolainst/.gitignore
  tests/kolainst/Makefile
  tests/kolainst/destructive/layering-local
  tests/kolainst/kolainst-build.sh
  tests/vmcheck/test-layering-local.sh
Labels: approved, lgtm

#2631 Remove cbindgen
  Cargo.lock
  Cargo.toml
  Makefile-rpm-ostree.am
  Makefile.bindings
  cbindgen.toml
  ci/installdeps.sh
  configure.ac
  packaging/make-git-snapshot.sh
  src/app/rpmostree-builtin-applylive.cxx
  src/app/rpmostree-builtin-shlib-backend.cxx
  src/app/rpmostree-builtin-status.cxx
  src/app/rpmostree-builtin-testutils.cxx
  src/app/rpmostree-compose-builtin-rojig.cxx
  src/app/rpmostree-compose-builtin-tree.cxx
  src/app/rpmostree-composeutil.cxx
  src/app/rpmostree-dbus-helpers.cxx
  src/app/rpmostree-ex-builtin-commit2rojig.cxx
  src/daemon/rpmostree-sysroot-core.cxx
  src/daemon/rpmostree-sysroot-upgrader.cxx
  src/libpriv/rpmostree-core.cxx
  src/libpriv/rpmostree-core.h
  src/libpriv/rpmostree-kernel.cxx
  src/libpriv/rpmostree-output.cxx
  src/libpriv/rpmostree-passwd-util.cxx
  src/libpriv/rpmostree-passwd-util.h
  src/libpriv/rpmostree-postprocess.cxx
  src/libpriv/rpmostree-postprocess.h
  src/libpriv/rpmostree-rust-prelude.h
  src/libpriv/rpmostree-util.cxx
  tests/common/libvm.sh
Labels: approved, lgtm

#2636 rust/client: Extend with more metadata for zincati
  rust/rpmostree-client/src/lib.rs
  rust/rpmostree-client/tests/parse.rs
Labels: approved, lgtm

#2642 app/override: Hint at `rpm-ostree override reset`
  src/app/rpmostree-override-builtins.cxx
Labels: approved, lgtm

#2634 compose/extensions: Handle no --base-rev
  rust/src/lib.rs
  rust/src/treefile.rs
  src/app/rpmostree-compose-builtin-tree.cxx
  tests/compose/test-basic-unified.sh
Labels: approved, lgtm

#2643 rust/client: derive(Debug, Clone)
  rust/rpmostree-client/src/lib.rs
Labels: approved, lgtm

#2646 daemon: Move a bit more deployment-variant code to Rust
  rust/src/daemon.rs
  src/daemon/rpmostreed-deployment-utils.cxx
Labels: approved, lgtm

#2651 rust: Relicense some GPL-2.0-or-later to Apache-2.0 OR MIT
  rust/src/cliwrap.rs
  rust/src/cliwrap/cliutil.rs
  rust/src/cliwrap/dracut.rs
  rust/src/countme.rs
  rust/src/countme/cookie.rs
  rust/src/countme/repo.rs
  rust/src/history.rs
Labels: approved, lgtm

#2652 rust: Support context attribute on CxxResult, use it more
  rust/src/countme/repo.rs
  rust/src/cxxrsutil.rs
  rust/src/history.rs
  rust/src/testutils.rs
Labels: approved, lgtm

#2653 tests: Drain vmcheck/test-misc-1 into kola/misc.sh
  tests/kolainst/nondestructive/misc.sh
  tests/vmcheck/test-misc-1.sh
Labels: approved

#2654 ci: Add composepost-checks.sh, drop a compose test
  .cci.jenkinsfile
  ci/composepost-checks.sh
  tests/compose/test-boot-location-modules.sh
Labels: approved

#2648 Move some small daemon layering lookup into Rust
  rust/src/daemon.rs
  rust/src/lib.rs
  rust/src/variant_utils.rs
  src/daemon/rpmostree-sysroot-upgrader.cxx
  src/daemon/rpmostreed-transaction-types.cxx
  src/libpriv/rpmostree-util.cxx
Labels: approved

#2693 Docs/compose server
  docs/compose-server.md
Labels: ok-to-test

#2696 Fix ambigous compose postprocess man entry
  src/app/rpmostree-compose-builtin-tree.cxx
Labels: ok-to-test

#2710 Help text on error: Transaction in progress #2341
  src/daemon/rpmostreed-sysroot.cxx
Labels: ok-to-test
