Repository coreos/rpm-ostree, pull requests merged in 2022-09, with the labels that each got.

#4008 ci(lint): add shell linter - Differential ShellCheck
  .github/workflows/ci.yaml
Labels: needs-ok-to-test

#4059 rhel8: rust: Bump to ostree-ext 0.8.7
  Cargo.lock
Labels: rhel8

#4060 [rhel8] cliwrap: Also inject /dev/random into cliwrap'd dracut
  rust/src/cliwrap/kernel_install.rs
Labels: rhel8

#4038 core: Get the kernel version from the kernel path
  src/libpriv/rpmostree-kernel.cxx
Labels: ok-to-test
