Repository coreos/rpm-ostree, pull requests merged in 2022-05, with the labels that each got.

#3652 libpriv/core: workaround libdnf vars path lookup
  src/libpriv/rpmostree-core.cxx
Labels: do-not-merge/hold

#3610 build: Add support for propagating RPM IMA signatures
  docs/treefile.md
  rust/src/lib.rs
  rust/src/treefile.rs
  src/libpriv/rpmostree-core.cxx
  src/libpriv/rpmostree-core.h
  src/libpriv/rpmostree-importer.cxx
  src/libpriv/rpmostree-importer.h
  src/libpriv/rpmostree-postprocess.cxx
Labels: for-next-release

#3691 rpmostreed-sysroot: Use G_IO_ERROR_BUSY for "Transaction in progress" error
  src/daemon/rpmostreed-sysroot.cxx
Labels: ok-to-test
